version: "2"
services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver:kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    ports: 
      - 9200:9200
      - 9300:9300
    networks:
      - kafkanet
  kibana: 
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    ports:
      - 5601:5601
    links: 
      - elasticsearch:elasticsearch
    networks:
      - kafkanet
    depends_on: ['elasticsearch']
  logstash: 
    image: docker.elastic.co/logstash/logstash:6.4.0
    container_name: logstash
    links: 
      - elasticsearch:elasticsearch
      - kafkaserver:kafkaserver
    networks:
      - kafkanet
    depends_on: ['elasticsearch', 'kafkaserver']
    volumes:
      - '/private/config-dir:/usr/share/logstash/pipeline/'
  apm-server:
    image: docker.elastic.co/apm/apm-server:6.4.0
    container_name: apm_server
    ports: ['8200:8200']
    command: --strict.perms=false -e
    networks:
      - kafkanet

networks:
  kafkanet:
    driver: bridge
